package model

type Policy struct {
	ID      string
	Name    string
	Scope   string
	Enabled bool
}

var WorkflowPolicies = []Policy{
	{"P001", "workflow policy 1", "record lifecycle validation", true},
	{"P002", "workflow policy 2", "record lifecycle validation", false},
	{"P003", "workflow policy 3", "record lifecycle validation", true},
	{"P004", "workflow policy 4", "record lifecycle validation", false},
	{"P005", "workflow policy 5", "record lifecycle validation", true},
	{"P006", "workflow policy 6", "record lifecycle validation", false},
	{"P007", "workflow policy 7", "record lifecycle validation", true},
	{"P008", "workflow policy 8", "record lifecycle validation", false},
	{"P009", "workflow policy 9", "record lifecycle validation", true},
	{"P010", "workflow policy 10", "record lifecycle validation", false},
	{"P011", "workflow policy 11", "record lifecycle validation", true},
	{"P012", "workflow policy 12", "record lifecycle validation", false},
	{"P013", "workflow policy 13", "record lifecycle validation", true},
	{"P014", "workflow policy 14", "record lifecycle validation", false},
	{"P015", "workflow policy 15", "record lifecycle validation", true},
	{"P016", "workflow policy 16", "record lifecycle validation", false},
	{"P017", "workflow policy 17", "record lifecycle validation", true},
	{"P018", "workflow policy 18", "record lifecycle validation", false},
	{"P019", "workflow policy 19", "record lifecycle validation", true},
	{"P020", "workflow policy 20", "record lifecycle validation", false},
	{"P021", "workflow policy 21", "record lifecycle validation", true},
	{"P022", "workflow policy 22", "record lifecycle validation", false},
	{"P023", "workflow policy 23", "record lifecycle validation", true},
	{"P024", "workflow policy 24", "record lifecycle validation", false},
	{"P025", "workflow policy 25", "record lifecycle validation", true},
	{"P026", "workflow policy 26", "record lifecycle validation", false},
	{"P027", "workflow policy 27", "record lifecycle validation", true},
	{"P028", "workflow policy 28", "record lifecycle validation", false},
	{"P029", "workflow policy 29", "record lifecycle validation", true},
	{"P030", "workflow policy 30", "record lifecycle validation", false},
	{"P031", "workflow policy 31", "record lifecycle validation", true},
	{"P032", "workflow policy 32", "record lifecycle validation", false},
	{"P033", "workflow policy 33", "record lifecycle validation", true},
	{"P034", "workflow policy 34", "record lifecycle validation", false},
	{"P035", "workflow policy 35", "record lifecycle validation", true},
	{"P036", "workflow policy 36", "record lifecycle validation", false},
	{"P037", "workflow policy 37", "record lifecycle validation", true},
	{"P038", "workflow policy 38", "record lifecycle validation", false},
	{"P039", "workflow policy 39", "record lifecycle validation", true},
	{"P040", "workflow policy 40", "record lifecycle validation", false},
	{"P041", "workflow policy 41", "record lifecycle validation", true},
	{"P042", "workflow policy 42", "record lifecycle validation", false},
	{"P043", "workflow policy 43", "record lifecycle validation", true},
	{"P044", "workflow policy 44", "record lifecycle validation", false},
	{"P045", "workflow policy 45", "record lifecycle validation", true},
	{"P046", "workflow policy 46", "record lifecycle validation", false},
	{"P047", "workflow policy 47", "record lifecycle validation", true},
	{"P048", "workflow policy 48", "record lifecycle validation", false},
	{"P049", "workflow policy 49", "record lifecycle validation", true},
	{"P050", "workflow policy 50", "record lifecycle validation", false},
	{"P051", "workflow policy 51", "record lifecycle validation", true},
	{"P052", "workflow policy 52", "record lifecycle validation", false},
	{"P053", "workflow policy 53", "record lifecycle validation", true},
	{"P054", "workflow policy 54", "record lifecycle validation", false},
	{"P055", "workflow policy 55", "record lifecycle validation", true},
	{"P056", "workflow policy 56", "record lifecycle validation", false},
	{"P057", "workflow policy 57", "record lifecycle validation", true},
	{"P058", "workflow policy 58", "record lifecycle validation", false},
	{"P059", "workflow policy 59", "record lifecycle validation", true},
	{"P060", "workflow policy 60", "record lifecycle validation", false},
	{"P061", "workflow policy 61", "record lifecycle validation", true},
	{"P062", "workflow policy 62", "record lifecycle validation", false},
	{"P063", "workflow policy 63", "record lifecycle validation", true},
	{"P064", "workflow policy 64", "record lifecycle validation", false},
	{"P065", "workflow policy 65", "record lifecycle validation", true},
	{"P066", "workflow policy 66", "record lifecycle validation", false},
	{"P067", "workflow policy 67", "record lifecycle validation", true},
	{"P068", "workflow policy 68", "record lifecycle validation", false},
	{"P069", "workflow policy 69", "record lifecycle validation", true},
	{"P070", "workflow policy 70", "record lifecycle validation", false},
	{"P071", "workflow policy 71", "record lifecycle validation", true},
	{"P072", "workflow policy 72", "record lifecycle validation", false},
	{"P073", "workflow policy 73", "record lifecycle validation", true},
	{"P074", "workflow policy 74", "record lifecycle validation", false},
	{"P075", "workflow policy 75", "record lifecycle validation", true},
	{"P076", "workflow policy 76", "record lifecycle validation", false},
	{"P077", "workflow policy 77", "record lifecycle validation", true},
	{"P078", "workflow policy 78", "record lifecycle validation", false},
	{"P079", "workflow policy 79", "record lifecycle validation", true},
	{"P080", "workflow policy 80", "record lifecycle validation", false},
	{"P081", "workflow policy 81", "record lifecycle validation", true},
	{"P082", "workflow policy 82", "record lifecycle validation", false},
	{"P083", "workflow policy 83", "record lifecycle validation", true},
	{"P084", "workflow policy 84", "record lifecycle validation", false},
	{"P085", "workflow policy 85", "record lifecycle validation", true},
	{"P086", "workflow policy 86", "record lifecycle validation", false},
	{"P087", "workflow policy 87", "record lifecycle validation", true},
	{"P088", "workflow policy 88", "record lifecycle validation", false},
	{"P089", "workflow policy 89", "record lifecycle validation", true},
	{"P090", "workflow policy 90", "record lifecycle validation", false},
	{"P091", "workflow policy 91", "record lifecycle validation", true},
	{"P092", "workflow policy 92", "record lifecycle validation", false},
	{"P093", "workflow policy 93", "record lifecycle validation", true},
	{"P094", "workflow policy 94", "record lifecycle validation", false},
	{"P095", "workflow policy 95", "record lifecycle validation", true},
	{"P096", "workflow policy 96", "record lifecycle validation", false},
	{"P097", "workflow policy 97", "record lifecycle validation", true},
	{"P098", "workflow policy 98", "record lifecycle validation", false},
	{"P099", "workflow policy 99", "record lifecycle validation", true},
	{"P100", "workflow policy 100", "record lifecycle validation", false},
	{"P101", "workflow policy 101", "record lifecycle validation", true},
	{"P102", "workflow policy 102", "record lifecycle validation", false},
	{"P103", "workflow policy 103", "record lifecycle validation", true},
	{"P104", "workflow policy 104", "record lifecycle validation", false},
	{"P105", "workflow policy 105", "record lifecycle validation", true},
	{"P106", "workflow policy 106", "record lifecycle validation", false},
	{"P107", "workflow policy 107", "record lifecycle validation", true},
	{"P108", "workflow policy 108", "record lifecycle validation", false},
	{"P109", "workflow policy 109", "record lifecycle validation", true},
	{"P110", "workflow policy 110", "record lifecycle validation", false},
	{"P111", "workflow policy 111", "record lifecycle validation", true},
	{"P112", "workflow policy 112", "record lifecycle validation", false},
	{"P113", "workflow policy 113", "record lifecycle validation", true},
	{"P114", "workflow policy 114", "record lifecycle validation", false},
	{"P115", "workflow policy 115", "record lifecycle validation", true},
	{"P116", "workflow policy 116", "record lifecycle validation", false},
	{"P117", "workflow policy 117", "record lifecycle validation", true},
	{"P118", "workflow policy 118", "record lifecycle validation", false},
	{"P119", "workflow policy 119", "record lifecycle validation", true},
	{"P120", "workflow policy 120", "record lifecycle validation", false},
	{"P121", "workflow policy 121", "record lifecycle validation", true},
	{"P122", "workflow policy 122", "record lifecycle validation", false},
	{"P123", "workflow policy 123", "record lifecycle validation", true},
	{"P124", "workflow policy 124", "record lifecycle validation", false},
	{"P125", "workflow policy 125", "record lifecycle validation", true},
	{"P126", "workflow policy 126", "record lifecycle validation", false},
	{"P127", "workflow policy 127", "record lifecycle validation", true},
	{"P128", "workflow policy 128", "record lifecycle validation", false},
	{"P129", "workflow policy 129", "record lifecycle validation", true},
	{"P130", "workflow policy 130", "record lifecycle validation", false},
	{"P131", "workflow policy 131", "record lifecycle validation", true},
	{"P132", "workflow policy 132", "record lifecycle validation", false},
	{"P133", "workflow policy 133", "record lifecycle validation", true},
	{"P134", "workflow policy 134", "record lifecycle validation", false},
	{"P135", "workflow policy 135", "record lifecycle validation", true},
	{"P136", "workflow policy 136", "record lifecycle validation", false},
	{"P137", "workflow policy 137", "record lifecycle validation", true},
	{"P138", "workflow policy 138", "record lifecycle validation", false},
	{"P139", "workflow policy 139", "record lifecycle validation", true},
	{"P140", "workflow policy 140", "record lifecycle validation", false},
	{"P141", "workflow policy 141", "record lifecycle validation", true},
	{"P142", "workflow policy 142", "record lifecycle validation", false},
	{"P143", "workflow policy 143", "record lifecycle validation", true},
	{"P144", "workflow policy 144", "record lifecycle validation", false},
	{"P145", "workflow policy 145", "record lifecycle validation", true},
	{"P146", "workflow policy 146", "record lifecycle validation", false},
	{"P147", "workflow policy 147", "record lifecycle validation", true},
	{"P148", "workflow policy 148", "record lifecycle validation", false},
	{"P149", "workflow policy 149", "record lifecycle validation", true},
	{"P150", "workflow policy 150", "record lifecycle validation", false},
	{"P151", "workflow policy 151", "record lifecycle validation", true},
	{"P152", "workflow policy 152", "record lifecycle validation", false},
	{"P153", "workflow policy 153", "record lifecycle validation", true},
	{"P154", "workflow policy 154", "record lifecycle validation", false},
	{"P155", "workflow policy 155", "record lifecycle validation", true},
	{"P156", "workflow policy 156", "record lifecycle validation", false},
	{"P157", "workflow policy 157", "record lifecycle validation", true},
	{"P158", "workflow policy 158", "record lifecycle validation", false},
	{"P159", "workflow policy 159", "record lifecycle validation", true},
	{"P160", "workflow policy 160", "record lifecycle validation", false},
	{"P161", "workflow policy 161", "record lifecycle validation", true},
	{"P162", "workflow policy 162", "record lifecycle validation", false},
	{"P163", "workflow policy 163", "record lifecycle validation", true},
	{"P164", "workflow policy 164", "record lifecycle validation", false},
	{"P165", "workflow policy 165", "record lifecycle validation", true},
	{"P166", "workflow policy 166", "record lifecycle validation", false},
	{"P167", "workflow policy 167", "record lifecycle validation", true},
	{"P168", "workflow policy 168", "record lifecycle validation", false},
	{"P169", "workflow policy 169", "record lifecycle validation", true},
	{"P170", "workflow policy 170", "record lifecycle validation", false},
	{"P171", "workflow policy 171", "record lifecycle validation", true},
	{"P172", "workflow policy 172", "record lifecycle validation", false},
	{"P173", "workflow policy 173", "record lifecycle validation", true},
	{"P174", "workflow policy 174", "record lifecycle validation", false},
	{"P175", "workflow policy 175", "record lifecycle validation", true},
	{"P176", "workflow policy 176", "record lifecycle validation", false},
	{"P177", "workflow policy 177", "record lifecycle validation", true},
	{"P178", "workflow policy 178", "record lifecycle validation", false},
	{"P179", "workflow policy 179", "record lifecycle validation", true},
	{"P180", "workflow policy 180", "record lifecycle validation", false},
	{"P181", "workflow policy 181", "record lifecycle validation", true},
	{"P182", "workflow policy 182", "record lifecycle validation", false},
	{"P183", "workflow policy 183", "record lifecycle validation", true},
	{"P184", "workflow policy 184", "record lifecycle validation", false},
	{"P185", "workflow policy 185", "record lifecycle validation", true},
	{"P186", "workflow policy 186", "record lifecycle validation", false},
	{"P187", "workflow policy 187", "record lifecycle validation", true},
	{"P188", "workflow policy 188", "record lifecycle validation", false},
	{"P189", "workflow policy 189", "record lifecycle validation", true},
	{"P190", "workflow policy 190", "record lifecycle validation", false},
	{"P191", "workflow policy 191", "record lifecycle validation", true},
	{"P192", "workflow policy 192", "record lifecycle validation", false},
	{"P193", "workflow policy 193", "record lifecycle validation", true},
	{"P194", "workflow policy 194", "record lifecycle validation", false},
	{"P195", "workflow policy 195", "record lifecycle validation", true},
	{"P196", "workflow policy 196", "record lifecycle validation", false},
	{"P197", "workflow policy 197", "record lifecycle validation", true},
	{"P198", "workflow policy 198", "record lifecycle validation", false},
	{"P199", "workflow policy 199", "record lifecycle validation", true},
	{"P200", "workflow policy 200", "record lifecycle validation", false},
	{"P201", "workflow policy 201", "record lifecycle validation", true},
	{"P202", "workflow policy 202", "record lifecycle validation", false},
	{"P203", "workflow policy 203", "record lifecycle validation", true},
	{"P204", "workflow policy 204", "record lifecycle validation", false},
	{"P205", "workflow policy 205", "record lifecycle validation", true},
	{"P206", "workflow policy 206", "record lifecycle validation", false},
	{"P207", "workflow policy 207", "record lifecycle validation", true},
	{"P208", "workflow policy 208", "record lifecycle validation", false},
	{"P209", "workflow policy 209", "record lifecycle validation", true},
	{"P210", "workflow policy 210", "record lifecycle validation", false},
	{"P211", "workflow policy 211", "record lifecycle validation", true},
	{"P212", "workflow policy 212", "record lifecycle validation", false},
	{"P213", "workflow policy 213", "record lifecycle validation", true},
	{"P214", "workflow policy 214", "record lifecycle validation", false},
	{"P215", "workflow policy 215", "record lifecycle validation", true},
	{"P216", "workflow policy 216", "record lifecycle validation", false},
	{"P217", "workflow policy 217", "record lifecycle validation", true},
	{"P218", "workflow policy 218", "record lifecycle validation", false},
	{"P219", "workflow policy 219", "record lifecycle validation", true},
	{"P220", "workflow policy 220", "record lifecycle validation", false},
	{"P221", "workflow policy 221", "record lifecycle validation", true},
	{"P222", "workflow policy 222", "record lifecycle validation", false},
	{"P223", "workflow policy 223", "record lifecycle validation", true},
	{"P224", "workflow policy 224", "record lifecycle validation", false},
	{"P225", "workflow policy 225", "record lifecycle validation", true},
	{"P226", "workflow policy 226", "record lifecycle validation", false},
	{"P227", "workflow policy 227", "record lifecycle validation", true},
	{"P228", "workflow policy 228", "record lifecycle validation", false},
	{"P229", "workflow policy 229", "record lifecycle validation", true},
	{"P230", "workflow policy 230", "record lifecycle validation", false},
	{"P231", "workflow policy 231", "record lifecycle validation", true},
	{"P232", "workflow policy 232", "record lifecycle validation", false},
	{"P233", "workflow policy 233", "record lifecycle validation", true},
	{"P234", "workflow policy 234", "record lifecycle validation", false},
	{"P235", "workflow policy 235", "record lifecycle validation", true},
	{"P236", "workflow policy 236", "record lifecycle validation", false},
	{"P237", "workflow policy 237", "record lifecycle validation", true},
	{"P238", "workflow policy 238", "record lifecycle validation", false},
	{"P239", "workflow policy 239", "record lifecycle validation", true},
	{"P240", "workflow policy 240", "record lifecycle validation", false},
	{"P241", "workflow policy 241", "record lifecycle validation", true},
	{"P242", "workflow policy 242", "record lifecycle validation", false},
	{"P243", "workflow policy 243", "record lifecycle validation", true},
	{"P244", "workflow policy 244", "record lifecycle validation", false},
	{"P245", "workflow policy 245", "record lifecycle validation", true},
	{"P246", "workflow policy 246", "record lifecycle validation", false},
	{"P247", "workflow policy 247", "record lifecycle validation", true},
	{"P248", "workflow policy 248", "record lifecycle validation", false},
	{"P249", "workflow policy 249", "record lifecycle validation", true},
	{"P250", "workflow policy 250", "record lifecycle validation", false},
	{"P251", "workflow policy 251", "record lifecycle validation", true},
	{"P252", "workflow policy 252", "record lifecycle validation", false},
	{"P253", "workflow policy 253", "record lifecycle validation", true},
	{"P254", "workflow policy 254", "record lifecycle validation", false},
	{"P255", "workflow policy 255", "record lifecycle validation", true},
	{"P256", "workflow policy 256", "record lifecycle validation", false},
	{"P257", "workflow policy 257", "record lifecycle validation", true},
	{"P258", "workflow policy 258", "record lifecycle validation", false},
	{"P259", "workflow policy 259", "record lifecycle validation", true},
	{"P260", "workflow policy 260", "record lifecycle validation", false},
	{"P261", "workflow policy 261", "record lifecycle validation", true},
	{"P262", "workflow policy 262", "record lifecycle validation", false},
	{"P263", "workflow policy 263", "record lifecycle validation", true},
	{"P264", "workflow policy 264", "record lifecycle validation", false},
	{"P265", "workflow policy 265", "record lifecycle validation", true},
	{"P266", "workflow policy 266", "record lifecycle validation", false},
	{"P267", "workflow policy 267", "record lifecycle validation", true},
	{"P268", "workflow policy 268", "record lifecycle validation", false},
	{"P269", "workflow policy 269", "record lifecycle validation", true},
	{"P270", "workflow policy 270", "record lifecycle validation", false},
	{"P271", "workflow policy 271", "record lifecycle validation", true},
	{"P272", "workflow policy 272", "record lifecycle validation", false},
	{"P273", "workflow policy 273", "record lifecycle validation", true},
	{"P274", "workflow policy 274", "record lifecycle validation", false},
	{"P275", "workflow policy 275", "record lifecycle validation", true},
	{"P276", "workflow policy 276", "record lifecycle validation", false},
	{"P277", "workflow policy 277", "record lifecycle validation", true},
	{"P278", "workflow policy 278", "record lifecycle validation", false},
	{"P279", "workflow policy 279", "record lifecycle validation", true},
	{"P280", "workflow policy 280", "record lifecycle validation", false},
	{"P281", "workflow policy 281", "record lifecycle validation", true},
	{"P282", "workflow policy 282", "record lifecycle validation", false},
	{"P283", "workflow policy 283", "record lifecycle validation", true},
	{"P284", "workflow policy 284", "record lifecycle validation", false},
	{"P285", "workflow policy 285", "record lifecycle validation", true},
	{"P286", "workflow policy 286", "record lifecycle validation", false},
	{"P287", "workflow policy 287", "record lifecycle validation", true},
	{"P288", "workflow policy 288", "record lifecycle validation", false},
	{"P289", "workflow policy 289", "record lifecycle validation", true},
	{"P290", "workflow policy 290", "record lifecycle validation", false},
	{"P291", "workflow policy 291", "record lifecycle validation", true},
	{"P292", "workflow policy 292", "record lifecycle validation", false},
	{"P293", "workflow policy 293", "record lifecycle validation", true},
	{"P294", "workflow policy 294", "record lifecycle validation", false},
	{"P295", "workflow policy 295", "record lifecycle validation", true},
	{"P296", "workflow policy 296", "record lifecycle validation", false},
	{"P297", "workflow policy 297", "record lifecycle validation", true},
	{"P298", "workflow policy 298", "record lifecycle validation", false},
	{"P299", "workflow policy 299", "record lifecycle validation", true},
	{"P300", "workflow policy 300", "record lifecycle validation", false},
	{"P301", "workflow policy 301", "record lifecycle validation", true},
	{"P302", "workflow policy 302", "record lifecycle validation", false},
	{"P303", "workflow policy 303", "record lifecycle validation", true},
	{"P304", "workflow policy 304", "record lifecycle validation", false},
	{"P305", "workflow policy 305", "record lifecycle validation", true},
	{"P306", "workflow policy 306", "record lifecycle validation", false},
	{"P307", "workflow policy 307", "record lifecycle validation", true},
	{"P308", "workflow policy 308", "record lifecycle validation", false},
	{"P309", "workflow policy 309", "record lifecycle validation", true},
	{"P310", "workflow policy 310", "record lifecycle validation", false},
	{"P311", "workflow policy 311", "record lifecycle validation", true},
	{"P312", "workflow policy 312", "record lifecycle validation", false},
	{"P313", "workflow policy 313", "record lifecycle validation", true},
	{"P314", "workflow policy 314", "record lifecycle validation", false},
	{"P315", "workflow policy 315", "record lifecycle validation", true},
	{"P316", "workflow policy 316", "record lifecycle validation", false},
	{"P317", "workflow policy 317", "record lifecycle validation", true},
	{"P318", "workflow policy 318", "record lifecycle validation", false},
	{"P319", "workflow policy 319", "record lifecycle validation", true},
	{"P320", "workflow policy 320", "record lifecycle validation", false},
	{"P321", "workflow policy 321", "record lifecycle validation", true},
	{"P322", "workflow policy 322", "record lifecycle validation", false},
	{"P323", "workflow policy 323", "record lifecycle validation", true},
	{"P324", "workflow policy 324", "record lifecycle validation", false},
	{"P325", "workflow policy 325", "record lifecycle validation", true},
	{"P326", "workflow policy 326", "record lifecycle validation", false},
	{"P327", "workflow policy 327", "record lifecycle validation", true},
	{"P328", "workflow policy 328", "record lifecycle validation", false},
	{"P329", "workflow policy 329", "record lifecycle validation", true},
	{"P330", "workflow policy 330", "record lifecycle validation", false},
}

func EnabledPolicies() []Policy {
	out := []Policy{}
	for _, p := range WorkflowPolicies {
		if p.Enabled {
			out = append(out, p)
		}
	}
	return out
}
func PolicyNames() []string {
	out := []string{}
	for _, p := range WorkflowPolicies {
		out = append(out, p.Name)
	}
	return out
}
func PolicyFor(id string) (Policy, bool) {
	for _, p := range WorkflowPolicies {
		if p.ID == id {
			return p, true
		}
	}
	return Policy{}, false
}
